# This CircleCI configuration executes 3 different jobs:
#   * build: Install dependencies and build static assets
#   * test: Run all unit and functional tests
#   * deploy: Push artifact code to a remote git repository.
#
# In this configuration, deployment happens regardless of testing outcome.
# Assuming you wait until tests pass before merging any PRs or deploying from dev
# to prod, this enables much faster local -> multidev deployment cycles without
# increasing risk.
#
# This configuration depends on the following environment variables being exported from
# the UI:
#
#   * TERMINUS_MACHINE_TOKEN
#
# It also depends on the following environment variables declared in .env/terminus.env:
#
#   * TERMINUS_SITE
#   * TERMINUS_ENV
#
version: 2.1

executors:
  php:
    docker:
      - image: lastcallmedia/php:7.4-dev
    environment:
      GIT_AUTHOR_NAME: 'Last Call Media Automation'
      GIT_AUTHOR_EMAIL: 'sysadmin@lastcallmedia.com'
    working_directory: /var/www/code

jobs:
  build:
    executor: php
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn cache
          keys:
            - site-yarn-v1-{{ checksum "yarn.lock" }}
            - site-yarn-v1-
      - run: {name: "Yarn install", command: "yarn install --pure-lockfile" }
      - save_cache:
          name: Save Yarn cache
          key: site-yarn-v1-{{ checksum "yarn.lock" }}
          paths: [ node_modules ]
      - restore_cache:
          name: Restore Composer cache
          keys:
            - site-composer-v2-{{ checksum "composer.lock" }}
            - site-composer-v2-
      - run: {name: 'Composer install', command: 'composer install -n'}
      - save_cache:
          name: Save Composer cache
          key: site-composer-v2-{{ checksum "composer.lock" }}
          paths: [ vendor, web/core, web/modules/contrib, web/themes/contrib ]
#      - run: {name: "Execute build", command: "gulp build" }
      # Temporary: Don't build Mannequin - see: https://lastcall.atlassian.net/browse/WIT-686?focusedCommentId=59121
      # - run: {name: "Build Mannequin", command: "vendor/bin/mannequin snapshot -o web/mannequin -c .mannequin.pantheon.php"}
      - persist_to_workspace:
          root: /var/www
          paths: [code]

  test:
    working_directory: /var/www/code
    docker:
      - image: lastcallmedia/php:7.4-dev # Primary image
        environment:
          DOCKER_ENV: ci
          APACHE_DOCROOT: /var/www/code/web
          MYSQL_USER: circle
          MYSQL_PASSWORD: circle
          MYSQL_DATABASE: circle
          MYSQL_HOST: 127.0.0.1
      - image: mysql:5.6
        environment:
          MYSQL_USER: circle
          MYSQL_PASSWORD: circle
          MYSQL_DATABASE: circle
          MYSQL_RANDOM_ROOT_PASSWORD: 1
    steps:
      - attach_workspace: {at: /var/www}
      - run:
          name: Prepare Environment
          command: |
            echo "source /var/www/code/.env/terminus.env" >> $BASH_ENV && source /var/www/code/.env/terminus.env
            mkdir /tmp/junit /tmp/artifacts web/sites/simpletest web/sites/default/files && chown www-data:www-data /tmp/junit web/sites/default/files web/sites/simpletest
            terminus auth:login --machine-token="$TERMINUS_MACHINE_TOKEN"
            terminus backup:info "$TERMINUS_SITE.$TERMINUS_ENV" --element=db --field=file > /tmp/db-cache-indicator
      # Run linting steps up front.  If these fail, they should provide fast feedback.
      #      - run: {name: 'ESLint', command: 'node_modules/.bin/eslint -f junit . > /tmp/junit/eslint.xml'}
      - run: {name: 'PHPCS', command: 'vendor/bin/phpcs --report-junit=/tmp/junit/phpcs.xml --report-summary'}
      # ---------- Superfluous tests disabled ----------
      #     Mannequin ommited, currently not compatible with D9 / PHP 7.4.
      #     - run: {name: 'Mannequin Snapshot', command: 'vendor/bin/mannequin snapshot -o /tmp/artifacts/mannequin'}
      #      - run: {name: 'Start Apache', command: 'docker-php-entrypoint apache2-foreground', background: true}
      #      - run: {name: 'Wait for MySQL', command: 'dockerize -wait tcp://localhost:3306 -timeout 10s'}
      #      - restore_cache: { name: 'Restore DB Cache', key: 'db-{{ checksum "/tmp/db-cache-indicator" }}'}
      #      - run: {name: 'Refresh Site', command: 'composer site:import -- -c /tmp/db-cache'}
      #      - save_cache: {name: 'Save DB Cache', key: 'db-{{ checksum "/tmp/db-cache-indicator" }}', paths: ['/tmp/db-cache']}
      #      - run: {name: 'Wait for Apache', command: 'dockerize -wait tcp://localhost:80 -timeout 5s'}
      # Run PHPUnit as www-data to support BrowserTestBase installing the site.
  #      - run: {name: 'Run PHPUnit', command: 'su -s /bin/bash www-data -c "vendor/bin/phpunit --log-junit=/tmp/junit/phpunit.xml"'}
  #      - run: {name: 'Run Behat', command: 'vendor/bin/behat --profile=ci -f junit -o /tmp/junit'}
  #      - store_test_results: { path: '/tmp/junit' }
  #      - store_artifacts: {path: '/tmp/artifacts'}

  deploy:
    executor: php
    steps:
      - attach_workspace: {at: /var/www}
      - run: {name: 'Create directory for terminus build tools', command: 'mkdir -p ~/.terminus/plugins'}
      - run: {name: 'Add terminus build tools', command: 'composer create-project --no-dev -d ~/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:^2.0.0'}
      - run: {name: 'Source environment variables', command: 'echo "source /var/www/code/.env/terminus.env" >> $BASH_ENV'}
      - run: {name: 'Terminus Login', command: 'terminus auth:login --machine-token="$TERMINUS_MACHINE_TOKEN"'}
      - run: {name: 'Export git variables', command: 'terminus connection:info --fields=git_host,git_port,git_url --format=json "$TERMINUS_SITE.dev" | bin/json-to-bash >> $BASH_ENV'}
      - run: {name: 'Trust host key', command: 'ssh-keyscan -p $GIT_PORT $GIT_HOST >> /etc/ssh/ssh_known_hosts'}
      - run: {name: 'Set git committer', command: 'git config --global user.email "$GIT_AUTHOR_EMAIL" && git config --global user.name "$GIT_AUTHOR_NAME"'}
      - run: {name: 'Lean Composer install', command: 'composer install --no-dev -o -n'}
      - run: {name: 'Push Artifact', command: 'node_modules/.bin/artifactsh -a $GIT_URL -b $CIRCLE_BRANCH'}
      - run: {name: 'Ensure multidev', command: 'test $CIRCLE_BRANCH == "master" || bin/create-artifact-environment-pantheon -b $CIRCLE_BRANCH -s $TERMINUS_ENV'}
      - run: {name: 'Set build secrets', command: 'terminus build:secrets:set "$TERMINUS_SITE.$TERMINUS_ENV" token "$GITHUB_TOKEN" --file=tokens.json'}
#      - run: {name: 'Prune multidev environments', command: 'bin/prune-artifact-environments-pantheon -p "p-*"'}
#      - run: {name: 'Prune branches', command: 'bin/prune-artifact-branches -a $GIT_URL -p "p-*"'}
workflows:
  version: 2
  build_test_release:
    jobs:
      - build
      - test:
#          context: org-global
          requires: [build]
      - deploy:
#          context: org-global
          requires: [build]
          filters:
            branches:
              only: ['/p-.*/', 'master']
